### ISSUE TITLE
MissingSubscriptionRegistration The subscription is not registered to use namespace 'Microsoft.Web'

### ISSUE THREAD

**Issue by pitsta** [SharePoint/PnP-Partner-Pack#239]
Hi there,

When running the OfficeDevPnp.PartnerPack solution. And following the video https://dev.office.com/blogs/automate-custom-solution-deployment-steps-at-office-365-and-azure. I get an exception error. 

ApplicationException: Exception while invoking endpoint https://management.azure.com/subscriptions/23b939a3-f9d8-4f29-ac7b-26e20330fb42/resourceGroups/pnp-partner-pack-ibiqs-resource-group/providers/Microsoft.Web/serverfarms/pnp-partner-pack-ibiqs-plan?api-version=2015-08-01.
 and 
HttpException: {"error":{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions."}}

I am using my Office 365 tenant and the same Azure account as my tenant.

Update:
Here is the error from the apps UI

System.ApplicationException: Exception while invoking endpoint https://management.azure.com/subscriptions/23b939a3-f9d8-4f29-ac7b-26e20330fb42/resourceGroups/pnp-partner-pack-ibiqs-resource-group/providers/Microsoft.Web/serverfarms/pnp-partner-pack-ibiqs-plan?api-version=2015-08-01. ---> System.Web.HttpException: {"error":{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.Web'. See https://aka.ms/rps-not-found for how to register subscriptions."}}
   --- End of inner exception stack trace ---
   at OfficeDevPnP.PartnerPack.Setup.Components.HttpHelper.<MakeHttpRequestAsync>d__11`1.MoveNext() in C:\Users\ShaunPitt\Documents\Visual Studio 2017\Projects\OfficeDevPnP.PartnetPack v2\OfficeDevPnP.PartnerPack.Setup\Components\HttpHelper.cs:line 356
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OfficeDevPnP.PartnerPack.Setup.Components.HttpHelper.<MakePutRequestForStringAsync>d__7.MoveNext() in C:\Users\ShaunPitt\Documents\Visual Studio 2017\Projects\OfficeDevPnP.PartnetPack v2\OfficeDevPnP.PartnerPack.Setup\Components\HttpHelper.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OfficeDevPnP.PartnerPack.Setup.Components.AzureManagementUtility.<CreateServicePlan>d__12.MoveNext() in C:\Users\ShaunPitt\Documents\Visual Studio 2017\Projects\OfficeDevPnP.PartnetPack v2\OfficeDevPnP.PartnerPack.Setup\Components\AzureManagementUtility.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OfficeDevPnP.PartnerPack.Setup.Components.SetupManager.<CreateAzureResourceGroup>d__14.MoveNext() in C:\Users\ShaunPitt\Documents\Visual Studio 2017\Projects\OfficeDevPnP.PartnetPack v2\OfficeDevPnP.PartnerPack.Setup\Components\SetupManager.cs:line 555
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OfficeDevPnP.PartnerPack.Setup.Components.SetupManager.<SetupPartnerPackAsync>d__1.MoveNext() in C:\Users\ShaunPitt\Documents\Visual Studio 2017\Projects\OfficeDevPnP.PartnetPack v2\OfficeDevPnP.PartnerPack.Setup\Components\SetupManager.cs:line 75

please help :-(

thank you
Shaun

**Comment by PaoloPia** [comment]
Thanks for your feedback. I've just updated the Setup Wizard, in order to register the "Microsoft.Web" provider before the creation of the App Service Plan, which is the stage in which the setup failed in your environment. Now the updated code is merged both in the DEV and MASTER branches.

**Comment by pitsta** [comment]
Hey thanks Paolo,
That was very quick to respond. I truly see the benefits in what you and the team are doing so thank you.
regards
Shaun
