### ISSUE TITLE
Automated Setup Not Publishing Website

### ISSUE THREAD

**Issue by davepoleon** [SharePoint/PnP-Partner-Pack#248]
Hi,

I am using the setup wizard to install the PnP Partner Pack, the wizard runs all the way through but at the end I am getting the default Azure "Your App Service app has been created" website page, it looks like the Partner Pack hasn't been published to the newly created site.

Everything else is there as expected, the certificate, the webjobs the infrastructure site etc.

I have tried a few times with the same result, any help would be much appreciated!

Regards

**Comment by karenwhy** [comment]
I have the same issue, however I do not have any of the Azure web jobs created either but everything else seems to be in place.

**Comment by andrewgaskins** [comment]
I am erroring out just after the app service is created. I get the following error:

System.Management.Automation.CmdletInvocationException: You cannot call a method on a null-valued expression. ---> System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. I guess it could be that you don't have the MSBuild v. 14.0 installed in your environment. Please check if you have the following registry key:

"hklm:\SOFTWARE\Microsoft\MSBuild\14.0"

Thanks.

**Comment by davepoleon** [comment]
Hi Paolo,

I do have MSBuild v 14.0 installed so I don't think it is that.
![msbuild](https://cloud.githubusercontent.com/assets/26538632/24896890/d0a26488-1e8e-11e7-93ef-afd08170f44c.PNG)

**Comment by PaoloPia** [comment]
Hi,
We found an issue in the setup wizard related to VS2017 and we fixed it. The effect of the issue was exactly what you described here. Right now, you should be able to properly setup the PnP Partner Pack using the latest version of the setup wizard either with VS2015 or VS2017. Thus, I will close this item but in case of any further issue, please let me know and I will be more than happy to re-open it and help you. Thanks.
