### ISSUE TITLE
Getting an error in the Scheduled Job to process "Save site as Provisioning Template" job

### ISSUE THREAD

**Issue by pankajsurti** [SharePoint/PnP-Partner-Pack#308]
*** The following is the log from the ScheduledJob *** 

The exception is :"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."

[02/01/2018 11:40:40 > a5b93a: SYS INFO] Status changed to Initializing
[02/01/2018 11:40:40 > a5b93a: SYS INFO] Run script 'OfficeDevPnP.PartnerPack.ScheduledJob.exe' with script host - 'WindowsScriptHost'
[02/01/2018 11:40:40 > a5b93a: SYS INFO] Status changed to Running
[02/01/2018 11:40:41 > a5b93a: INFO] Starting job
[02/01/2018 11:40:42 > a5b93a: INFO] Processing jobs in Site: PnP Partner Pack - Infrastructural Site
[02/01/2018 11:40:43 > a5b93a: INFO] Processing job: 542e4e75-a109-4fb9-a8dd-5a9185897741 - Owner: admin@M365x436044.onmicrosoft.com - Title: Test2Template
[02/01/2018 11:41:24 > a5b93a: INFO] Exception occurred: {"error":{"code":"-1, Microsoft.SharePoint.Client.ResourceNotFoundException","message":{"lang":"en-US","value":"Cannot find resource for the request SP.RequestContext.current/web/tenantappcatalog/."}}}
[02/01/2018 11:41:24 > a5b93a: INFO] Stack Trace:
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.Core.ALM.AppManager.<BaseGetAvailableAsync>d__34.MoveNext()
[02/01/2018 11:41:24 > a5b93a: INFO] --- End of stack trace from previous location where exception was thrown ---
[02/01/2018 11:41:24 > a5b93a: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[02/01/2018 11:41:24 > a5b93a: INFO]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.Core.ALM.AppManager.GetAvailable()
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectApplicationLifecycleManagement.ExtractObjects(Web web, ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
[02/01/2018 11:41:24 > a5b93a: INFO]    at Microsoft.SharePoint.Client.WebExtensions.GetProvisioningTemplate(Web web, ProvisioningTemplateCreationInformation creationInfo)
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.SharePoint.SharePointProvisioningRepository.SaveProvisioningTemplateInternal(ClientContext context, GetProvisioningTemplateJob job, Boolean globalRepository) in C:\PnPPatnerPack\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\SharePoint\SharePointProvisioningRepository.cs:line 192
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.SharePoint.SharePointProvisioningRepository.SaveGlobalProvisioningTemplate(GetProvisioningTemplateJob job) in C:\PnPPatnerPack\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\SharePoint\SharePointProvisioningRepository.cs:line 130
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningTemplateJobHandler.RunGetProvisioningTemplateJob(GetProvisioningTemplateJob job) in C:\PnPPatnerPack\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\ProvisioningTemplateJobHandler.cs:line 30
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningTemplateJobHandler.RunJobInternal(ProvisioningJob job) in C:\PnPPatnerPack\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\ProvisioningTemplateJobHandler.cs:line 16
[02/01/2018 11:41:24 > a5b93a: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job) in C:\PnPPatnerPack\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Infrastructure\Jobs\Handlers\ProvisioningJobHandler.cs:line 46
[02/01/2018 11:41:24 > a5b93a: INFO] 
[02/01/2018 11:41:24 > a5b93a: INFO] Ending job
[02/01/2018 11:41:24 > a5b93a: SYS INFO] Status changed to Success

**Comment by pankajsurti** [comment]
OK. I was able to find out cause of the above exception. I am using the demo.microsoft.com O365 tenant. The demo tenant does not have App Catalog. Once I created the app catalog I was able to get pass the above exception. I do see now the .PnP template file in the "PnPProvisioningTemplate" library under PnP Partnet Pack - Infrastructure Site.
