### ISSUE TITLE
Scheduled Job errors with AzureADAuth (AppOnly)

### ISSUE THREAD

**Issue by GrumpyWookie** [SharePoint/PnP-Partner-Pack#323]
Hello,

Have been able to deploy the site colleciton, and webapp - but having troubles with the ScheduledJob - and the AppOnly permissions.

I've re-done the entire solution - and checked each step of the way.    
But - still getting an error within _OfficeDevPnP.Core.AuthenticationManager_.

YES - I've checked my client id, and secret - and certificate thumbprint - all seem to be OK.

This is within the code for the Scheduled Job >>

FILE : Program.cs

            job.UseAzureADAppOnlyAuthentication(
                PnPPartnerPackSettings.ClientId,
                PnPPartnerPackSettings.Tenant,
                PnPPartnerPackSettings.AppOnlyCertificate);

I've verified within "console.writeline" that the above values are correct.

Checking within the WebJob console shows this >>
[02/15/2018 07:12:56 > 60bc6a: INFO]  |    at OfficeDevPnP.Core.AuthenticationManager.<>c__DisplayClass36_0.<**GetAzureADAppOnlyAuthenticatedContext**>b__0(Object sender, WebRequestEventArgs args)
[02/15/2018 07:12:56 > 60bc6a: INFO]    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientRuntimeContext.OnExecutingWebRequest(WebRequestEventArgs args)
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContext.GetWebRequestExecutor()
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContext.GetFormDigestInfoPrivate()
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContext.EnsureFormDigest()
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
[02/15/2018 07:12:56 > 60bc6a: INFO]    at Microsoft.SharePoint.Client.ClientObjectExtensions.EnsureProperty[T,TResult](T clientObject, Expression`1 propertySelector)

Is there a configuration I've missed ??    Or OAuth has changed for the tenant ?  

Any help would be great - I've spent a day or more trying to figure it out.

Thanks in advance...

**Comment by HiltonGiesenow** [comment]
Hey GrumpyWookie,

I set mine up a few weeks ago and thankfully it's working fine so maybe an extra pair or eyes will help. What error are you actually getting (I don't see it in your post, maybe just my eyes misbehaving :->)
